language: java

branches:
  except:
    - /^feature.*$/
  
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
