language: java

branches:
  except:
    - /^feature.*$/
  
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install:
  - chmod +x gradlew

after_script:
  - ./gradlew publishGhPages