coverage:
  precision: 0         # how many decimal places to display in the UI: 0 <= value <= 4
  round: up            # how coverage is rounded: down/up/nearest
  range: 50...80      # custom range of coverage colors from red -> yellow -> green

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes           # must be yes|true to enable this status
        target: 80%            # specify the target coverage for each commit status
                               #   option: "auto" (must increase from parent commit or pull request base)
                               #   option: "X%" a static target percentage to hit

    patch:                     # pull requests only: this commit status will measure the
                               # entire pull requests Coverage Diff. Checking if the lines
                               # adjusted are covered at least X%.
      default:
        enabled: yes             # must be yes|true to enable this status
        target: 80%              # specify the target "X%" coverage to hit

  ignore:          # files and folders that will be removed during processing
    - "tests/*"
    - "demo/*.rb"

  fixes:           # [advanced] in rare cases the report tree is invalid, specify adjustments here
    - "old_path::new_path"
